version: "3.8"

services:

  jupiter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - ./jupyter/work:/home/jovyan/work

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./config/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

networks:
  events:
    driver: bridge