version: "3.8"

services:

  jupiter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - ./jupyter/work:/home/jovyan/work

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./config/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
#    command: --init-file /data/application/init.sql
    volumes:
#      - ./init.sql:/data/application/init.sql
      - ./data/db:/var/lib/mysql
    ports:
      - "6033:3306"
    environment:
      - TZ=Europe/Moscow
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=asutp
      - MARIADB_PASSWORD=asutp
      - MARIADB_ROOT_PASSWORD=asutp
    #    entrypoint: mysql -uroot -ptgbot -e "create database huobibotdb_dev DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci";

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    environment:
      TZ: Europe/Moscow
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - mariadb

networks:
  events:
    driver: bridge